[[question]]
category = "Geography"
difficulty = "easy"
text = "What is the capital of France?"
options = ["Paris", "Berlin", "Madrid", "Rome"]
answer = "Paris"
feedback = "Paris is the capital and largest city of France."

[[question]]
category = "Mathematics"
difficulty = "medium"
text = "What is 2 + 2?"
options = ["3", "4", "5", "6"]
answer = "4"
feedback = "2 + 2 equals 4."

[[question]]
category = "Literature"
difficulty = "hard"
text = "Who wrote 'To Kill a Mockingbird'?"
options = ["Harper Lee", "Mark Twain", "J.K. Rowling", "Ernest Hemingway"]
answer = "Harper Lee"
feedback = "'To Kill a Mockingbird' was written by Harper Lee."
